### ISSUE TITLE
How to search on an auto-generated ObjectId?

### ISSUE THREAD

**Issue by mieel** [nightroman/Mdbc#24]
I made a document with
`{ "_id" : ObjectId("5cb87cdd73116924e09a36c2")}`

I can find it in mongo shell with this command  `db.Event.find(ObjectId('5cb87cdd73116924e09a36c2'))`

But I cant get the `get-Mdbcdata `cmdlet to retrieve this document

I tried these 
```
$query = "{`"_id`": ObjectId(`"5cb87cdd73116924e09a36c2`")}"
Get-MdbcData -Query $query

Get-MdbcData (New-MdbcQuery _id -EQ 'ObjectId("5cb87cdd73116924e09a36c2")'   )
```

**Comment by nightroman** [comment]
What is the type of `{ "_id" : ObjectId("5cb87cdd73116924e09a36c2")}`?

**Comment by nightroman** [comment]
Hmm, it's literally the `ObjectId` type (12 byte). I used to think that it is a Guid-like and just used Guid's in all my tasks.

To be honest, I do not know yet what you can do in your case. Maybe convert your string to Guid as described [here](https://stackoverflow.com/questions/5514111/convert-net-guid-to-mongodb-objectid) and use this Guid instead of `'ObjectId("5cb87cdd73116924e09a36c2")'`.

**Comment by nightroman** [comment]
Ah, here it is, try

```powershell
New-MdbcQuery _id -EQ ([MongoDB.Bson.ObjectId]"5cb87cdd73116924e09a36c2")
```

**Comment by mieel** [comment]
Thanks mate, works like a charm🙌

**Comment by nightroman** [comment]
@robinmalik Make and specify a filter expression, not just a value (id)

```
Get-MdbcData @{_id = [MongoDB.Bson.ObjectId]"608c2b570f4d67879abae51b"}
```

**Comment by robinmalik** [comment]
Fantastic, that works. Was just about to blow away the data to insert a guid alongside each document in the database so I could update them later on but now I don't have to. Thank you for such a quick reply!
