### ISSUE TITLE
When accessing a free MongoDB cluster I see the following error.

### ISSUE THREAD

**Issue by potnoddle** [nightroman/Mdbc#60]
I can now connect, however as soon try to get some data it fails. This errors only happens on MondoDB, azure works fine.
```
$conn = Connect-Mdbc -ConnectionString $connStr -DatabaseName $dbName -CollectionName $collectionName
$db = Get-MdbcDatabase -Name $dbName -Verbose
$collection = Get-MdbcCollection -Database $db -Name $collectionName

Get-MdbcData -Collection $Collection @{}
```

```
Get-MdbcData : Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1.
At C:\Users\potno\source\repos\Fanatic\Resources\NoSQL\ImportJson-MongoDB.ps1:27 char:1
+ Get-MdbcData -Collection $Collection @{}
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MdbcData], MongoAuthenticationException
    + FullyQualifiedErrorId : Mdbc,Mdbc.Commands.GetDataCommand
```

**Comment by nightroman** [comment]
I have not seen this kind of errors and do not know anything anything about them. I am not sure that the problem is Mdbc. If you prove this, i.e. you can do something using the C# driver (which Mdbc uses) but cannot by Mdbc then I will investigate further.

Try search the internet, the problem is kind of known
https://stackoverflow.com/questions/44513786/error-on-mongodb-authentication

**Comment by nightroman** [comment]
> I can now connect, however as soon try to get some data it fails

I would say you cannot connect. Connection is lazy it only actually happens when you try to get/set some data. Try a different command like I suggested before, does it work?

```
Connect-Mdbc -ConnectionString $connStr -DatabaseName *
```
